[package]
name = "knoll"
authors = ["Geoffrey Washburn <geoff@washburght.org>"]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/gawashburn/knoll"
categories = ["command-line-utilities"]

[dependencies]
