name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    environment: Coverage

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select toolchain
      uses: dtolnay/rust-toolchain@nightly
    - name: Test
      run: cargo test --all-features --no-fail-fast
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-C instrument-coverage'
        RUSTDOCFLAGS: '-C instrument-coverage'
    - name: Coverage report
      id: coverage
      uses: actions-rs/grcov@v0.1
    - name: Coveralls upload
      uses: coverallsapp/github-action@v2
      with:
        path-to-lcov: ${{ steps.coverage.outputs.report }}
    
